services:
  redis:
    image: redis:7-alpine
    container_name: aniguess-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    container_name: aniguess-postgres
    environment:
      POSTGRES_DB: aniguess_dev
      POSTGRES_USER: aniguess
      POSTGRES_PASSWORD: aniguess_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  default:
    name: aniguess-dev-network
